apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin    
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only  
  initdb.sql: |
    DROP TABLE IF EXISTS `Employee`;
    CREATE TABLE `Employee` (
        `id` int(6) unsigned NOT NULL AUTO_INCREMENT,
        `name` varchar(30) NOT NULL,
        `city` varchar(30) NOT NULL,
        PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
