apiVersion: apps/v1
kind: Deployment
metadata:
   name: myapp-deployment
spec:
   replicas: 2
   selector:
     matchLabels:
       app: myapp
   strategy:
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
     type: RollingUpdate
   template:
     metadata:
       labels:
         app: myapp
     spec:
       containers:
       - name: myapp
         image: myapp:{{VER}}
         imagePullPolicy: Never
         ports:
         - containerPort: 8088
